### ISSUE TITLE
Buffer without borders

### ISSUE THREAD

**Issue by brk0v** [Fabianlindfors/fdb-object-store#1]
I think, it should be

```
n, err := reader.Read(buffer)
...
tr.Set(tuple.Tuple{name, "data", i}, buffer[:n])
```

https://github.com/Fabianlindfors/fdb-object-store/blob/8fbabc5d5a68b62ee71ab316b86e1143fbf584da/main.go#L59

**Comment by fabianlindfors** [comment]
Thank you! I changed this in 0fff4384a97175f8761eab70da7cb6effb5c2dfc. :)
